title: Imdrasil Homebrew Stuff
email: moranibaca@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imdrasil.github.io"
github_username: imdrasil

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - src

source: src
destination: _src
