title: Imdrasil Homebrew Stuff
email: moranibaca@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imdrasil.github.io"
github_username:  imdrasil
source: site

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
